"""Schema and behaviour guards for the L3 capability catalog + its aggregation.

The catalog (``data/android_api_map.json``) is GENERATED by
``scripts/gen_capability_catalog.py`` from a curated selection (issue #30), but the
generator needs an AOSP dataset checkout that CI does not have — so the guards that
re-run it skip there, and the dataset-free ones at the bottom of this file are what
actually holds in CI. These exist because each failure mode has already happened or
would silently corrupt the aggregate report as the file grows:

1. a FIELD descriptor sits in a table looked up with ``find_call_sites_to`` — it
   matches nothing, forever, and no error is raised (three such entries shipped
   from 2026-05 to 2026-08 and were counted in ``catalog_size`` the whole time);
2. the two metadata axes leak into each other, which is what makes the aggregate
   Counter a measure of tagging density rather than of the APK;
3. the vocabulary drifts — ``DYNAMIC`` next to ``REFLECTION`` double-counted the
   same call sites under two names and occupied the top two report slots;
4. a tag is repeated inside one entry's list, which reproduces (3) while passing
   every set-based guard.

The schema guards are catalog-only, so they run in CI without an APK. The
behaviour guards at the bottom use a STUB dk (no corpus either) to pin decisions a
schema check cannot see: which axes ``only_categories`` matches, that an unknown
tag raises, the per-call-site aggregation scope, and that ``flags`` survives all
three layers (raw → SDK → MCP) — each of those was individually revertible with a
green suite before these were added.
"""

import json
import pathlib
from collections import Counter
from pathlib import Path

import pytest
from conftest import require_corpus_shape

from dexllm import capability

CATALOG = (
    Path(__file__).resolve().parents[1]
    / "src"
    / "dexllm"
    / "data"
    / "android_api_map.json"
)

# The closed `categories` vocabulary, PINNED. The catalog declares the same set in
# `category_vocabulary` (so `summarize_capabilities` can validate `only_categories`
# at runtime and a consumer can enumerate it); this copy exists so that CHANGING it
# is a conscious edit in two places — the only thing standing between a 10x bigger
# catalog and an unusable taxonomy. The two are asserted equal below.
CATEGORY_VOCABULARY = {
    # domains
    "ACCOUNTS",
    "BLUETOOTH",
    # BIOMETRIC / CLIPBOARD / DEVICE_ADMIN / KEYSTORE / NOTIFICATIONS /
    # PACKAGE_INSTALL / SCHEDULING / SCREEN_CAPTURE / USAGE_STATS arrived with the
    # dexllm#30 enrichment: every one of those
    # surfaces is permission-LESS or gated by a non-`dangerous` permission, so no
    # projection of the AOSP annotation map reaches them — they are exactly the
    # part of the catalog that has to be curated.
    # CALENDAR / CALL_LOG / CONTACTS arrived with the field-descriptor keys
    # (dexllm#36): an app reaches those providers by READING a CONTENT_URI
    # constant, so before field keys existed the catalog had no way to express
    # them and the three domains were absent from the vocabulary entirely.
    "CALENDAR",
    "CALL_LOG",
    "CAMERA",
    "CONTACTS",
    "LOCATION",
    "MICROPHONE",
    "NETWORK_IO",
    "PACKAGE_INFO",
    "SETTINGS",
    "SMS",
    "STORAGE",
    "TELEPHONY",
    "WEBVIEW",
    "WIFI",
    # behaviours. No ACCESSIBILITY: the abuse surface
    # (`AccessibilityService#getRootInActiveWindow` and friends) is invoked on
    # `this` inside the app's own subclass, so a dex records it under THAT class
    # and no `find_call_sites_to` key can name it — see the generator's note.
    "BIOMETRIC",
    "CLIPBOARD",
    "CRYPTO",
    "DEVICE_ADMIN",
    "DYNAMIC_LOAD",
    "KEYSTORE",
    "NATIVE_CODE",
    "NOTIFICATIONS",
    "PACKAGE_INSTALL",
    "PROCESS_EXEC",
    "REFLECTION",
    "SCHEDULING",
    "SCREEN_CAPTURE",
    "USAGE_STATS",
}

# The closed `flags` vocabulary — the orthogonal axis: cross-domain concerns a
# domain tag cannot express.
FLAG_VOCABULARY = {"IDENTIFIER"}


def _catalog():
    return json.loads(CATALOG.read_text())


def _entries():
    return _catalog()["entries"]


@pytest.fixture
def write_catalog(tmp_path_factory):
    """Write an override catalog to a fresh temp dir and return its path.

    A fresh directory per call because `datadir` caches by RESOLVED path (#43), so
    reusing one would serve the first catalog to every later test. Through
    `tmp_path_factory` rather than a bare `mkdtemp`, which the first cut used and
    which never cleaned up — 117 `/tmp/capcat*` directories had accumulated.
    """

    def _write(catalog):
        d = tmp_path_factory.mktemp("capcat")
        (d / "android_api_map.json").write_text(json.dumps(catalog))
        return str(d)

    return _write


def test_every_catalog_key_is_a_method_or_field_descriptor():
    """A key is ``Lcls;->name(proto)ret`` OR ``Lcls;->NAME:Ltype;``.

    INVERTED at dexllm#36. This used to reject a FIELD descriptor outright,
    because `summarize_capabilities` resolved every key with `find_call_sites_to`
    and a field key therefore matched nothing on every APK while still inflating
    `catalog_size` — three `CONTENT_URI` entries shipped that way and were deleted.
    The lookup now dispatches on the key's shape, so a field key is a first-class
    form and the rule is that a key must be one of the two, not that it must be a
    method. A third shape is still dead weight, which is what this now guards.
    """
    bad = []
    for key in _entries():
        cls, sep, member = key.partition(";->")
        if not sep or not cls.startswith("L") or not member:
            bad.append(key)
        elif "(" in member:  # method: a complete proto, and a return type after it
            if not member.endswith(tuple("VZBSCIJFD;[")) or ")" not in member:
                bad.append(key)
        elif ":" not in member or not member.split(":", 1)[1]:  # field: NAME:type
            bad.append(key)
    assert not bad, f"catalog keys that are neither a method nor a field: {bad}"

    # …and BOTH forms are actually present, or the dispatch this pins is untested
    # by the bundled catalog and the inversion above would be a claim, not a check.
    forms = {"(" in k.partition(";->")[2] for k in _entries()}
    assert forms == {True, False}, f"the catalog carries only one key form: {forms}"


def test_category_and_flag_axes_stay_disjoint():
    """No tag may appear on both axes.

    ``categories`` counts are only meaningful because they are a single axis; a tag
    living on both would be counted twice for one call site and re-create exactly
    the inflation the two-axis split removes.

    NON-DISCRIMINATING by design: it also passes against the pre-``flags`` catalog,
    where the second axis is empty. It guards the drift ahead, not the fix behind.
    """
    entries = _entries()
    cats = {c for e in entries.values() for c in e.get("categories", [])}
    flags = {f for e in entries.values() for f in e.get("flags", [])}
    assert not (cats & flags), f"tags on both axes: {sorted(cats & flags)}"


def test_vocabularies_are_closed():
    """No entry may carry a tag outside the declared vocabulary.

    This is what stops an ad-hoc tag — a synonym, a severity, a restatement of the
    key — from entering as the catalog grows. The reverse direction (a declared tag
    nothing uses) is deliberately NOT asserted: it is harmless (``only_categories``
    accepts it and correctly reports nothing), while asserting it would break on any
    entry deletion and forbid declaring a tag before filling it.
    """
    entries = _entries()
    cats = {c for e in entries.values() for c in e.get("categories", [])}
    flags = {f for e in entries.values() for f in e.get("flags", [])}
    assert not (
        cats - CATEGORY_VOCABULARY
    ), f"undeclared categories: {sorted(cats - CATEGORY_VOCABULARY)}"
    assert not (
        flags - FLAG_VOCABULARY
    ), f"undeclared flags: {sorted(flags - FLAG_VOCABULARY)}"


def test_catalog_declares_the_pinned_vocabulary():
    """The catalog's own declaration must equal the set pinned in this file.

    ``summarize_capabilities`` validates ``only_categories`` against the catalog's
    ``category_vocabulary`` / ``flag_vocabulary``, so those keys are the runtime
    contract. Pinning the same set here is what makes widening it a conscious edit
    rather than a side effect of adding an entry.
    """
    catalog = _catalog()
    assert set(catalog["category_vocabulary"]) == CATEGORY_VOCABULARY
    assert set(catalog["flag_vocabulary"]) == FLAG_VOCABULARY


def test_no_entry_repeats_a_tag():
    """A tag repeated inside one entry's list would be counted twice per call site.

    That is exactly the inflation the two-axis split removed (``REFLECTION`` and
    ``DYNAMIC`` double-counting the same sites), reachable again through the bulk
    load the module docstring plans for, where merging two sources duplicates rows.
    The emitter dedupes defensively; this keeps the bundled catalog honest.
    """
    dup = {
        key: axis
        for key, e in _entries().items()
        for axis in ("categories", "flags")
        if len(e.get(axis, [])) != len(set(e.get(axis, [])))
    }
    assert not dup, f"entries repeating a tag: {dup}"


def test_tag_and_permission_values_are_lists_of_strings():
    """``categories`` / ``flags`` / ``permissions`` must each be a list of strings.

    A bare string passes every other guard and is then iterated CHARACTER-wise by
    the emitter (``flags: "IDENTIFIER"`` → ``{'I': n, 'D': n, …}``) — silent
    corruption with no exception. ``null`` raises deep inside the aggregation.
    """
    bad = []
    for key, e in _entries().items():
        for axis in ("categories", "flags", "permissions"):
            if axis not in e:
                continue
            v = e[axis]
            if not isinstance(v, list) or not all(isinstance(x, str) for x in v):
                bad.append((key, axis, v))
    assert not bad, f"non list-of-str values: {bad}"


def test_every_entry_carries_at_least_one_category():
    """``categories`` is the primary axis — an entry without one is invisible to
    ``only_categories`` filtering and contributes nothing to the report's grouping.

    NON-DISCRIMINATING by design: the pre-patch catalog satisfied it too. It is the
    invariant stated so a future bulk load cannot quietly add untagged rows.
    """
    missing = [k for k, e in _entries().items() if not e.get("categories")]
    assert not missing, f"entries with no category: {missing}"


# ── behaviour guards (stub dk — no corpus needed) ────────────────────────────


class _Site:
    """Minimal stand-in for a CallSite: the aggregation reads one attribute."""

    def __init__(self, caller):
        self.caller_descriptor = caller


class _StubDk:
    """A dk answering from {descriptor: [callers]} maps — one per key FORM.

    A FIELD key resolves through `find_methods_reading_field`, which returns
    method descriptors rather than call sites (dexllm#36), so the stub needs both
    lookups: `summarize_capabilities` picks one by the key's shape. That is also
    the contract note for any duck-typed `dk` stand-in — a catalog carrying field
    keys now requires the field lookup too.
    """

    def __init__(self, sites, reads=None):
        self._sites = sites
        self._reads = reads or {}

    def find_call_sites_to(self, descriptor):
        return [_Site(c) for c in self._sites.get(descriptor, ())]

    def find_methods_reading_field(self, descriptor):
        return list(self._reads.get(descriptor, ()))


_GET_DEVICE_ID = "Landroid/telephony/TelephonyManager;->getDeviceId()Ljava/lang/String;"
_FOR_NAME = "Ljava/lang/Class;->forName(Ljava/lang/String;)Ljava/lang/Class;"


def test_only_categories_matches_either_axis():
    """A flag must stay usable as a filter, not just as a reported value.

    `IDENTIFIER` moved from `categories` to `flags` in 0.2. If the selection gate
    read only the `categories` axis, `only_categories={"IDENTIFIER"}` — the most
    obvious triage query the catalog supports — would return an empty report while
    the unfiltered run still shows `flags={'IDENTIFIER': …}`: visible but
    unselectable.

    Verified discriminating against the exact regression (reverting the gate to
    `want & set(cats)` fails this test). It also passes against pre-0.2 HEAD, for a
    different reason — there `IDENTIFIER` was still a category.
    """
    from dexllm.capability import summarize_capabilities

    dk = _StubDk({_GET_DEVICE_ID: ["La/B;->m()V"], _FOR_NAME: ["La/B;->n()V"]})

    by_flag = summarize_capabilities(dk, only_categories={"IDENTIFIER"})
    assert by_flag.matched_apis == 1
    assert by_flag.api_hits[0].api_signature == _GET_DEVICE_ID

    by_category = summarize_capabilities(dk, only_categories={"REFLECTION"})
    assert by_category.matched_apis == 1
    assert by_category.api_hits[0].api_signature == _FOR_NAME


def test_unknown_only_categories_tag_raises_instead_of_reporting_nothing():
    """A stale tag must fail loudly.

    The 0.2 normalisation deleted 17 tag names. A rule hardcoding one of them would
    otherwise get a well-formed report with `matched_apis=0`, byte-identical to the
    correct answer for an APK that genuinely exercises none of that domain.
    """
    from dexllm.capability import summarize_capabilities

    dk = _StubDk({_FOR_NAME: ["La/B;->n()V"]})
    with pytest.raises(ValueError, match="DYNAMIC"):
        summarize_capabilities(dk, only_categories={"DYNAMIC"})
    # a valid tag alongside an invalid one must still raise (no partial credit)
    with pytest.raises(ValueError, match="HASH"):
        summarize_capabilities(dk, only_categories={"REFLECTION", "HASH"})


def test_flags_are_counted_per_call_site_like_categories():
    """Pins the aggregation SCOPE, which no schema check can see.

    `report.flags` counts INVOCATIONS (as `permissions` and `categories` do), not
    matched APIs and not distinct callers. Moving the two counting lines out of the
    per-site loop turns 3 into 1; deduping by caller (a plausible refactor, since
    `hit.callers` is already a set) turns 3 into 2.

    The stub REPEATS a caller on purpose: with three distinct callers the per-site
    and per-caller readings coincide, and the caller-dedupe regression passes. Real
    APKs have the repeated shape — a2dp.Vol calls `requestLocationUpdates` 3 times
    from one method.
    """
    from dexllm.capability import summarize_capabilities

    dk = _StubDk({_GET_DEVICE_ID: ["La/B;->m()V", "La/B;->m()V", "La/C;->m()V"]})
    r = summarize_capabilities(dk)
    assert r.total_call_sites == 3
    assert r.flags == {"IDENTIFIER": 3}
    assert r.categories == {"TELEPHONY": 3}
    # …while the caller SET collapses the repeat, which is what makes the two
    # readings distinguishable here.
    assert r.api_hits[0].callers == {"La/B;->m()V", "La/C;->m()V"}
    assert r.api_hits[0].call_site_count == 3
    # the per-hit list stays per-API (one entry, not repeated per site)
    assert r.api_hits[0].flags == ["IDENTIFIER"]


def test_a_repeated_tag_is_not_counted_twice(tmp_path):
    """The emitter dedupes a malformed entry rather than inflating its count.

    A duplicate is not a fact to count twice — counting it reproduces exactly the
    `REFLECTION`/`DYNAMIC` double-count that motivated the 0.2 taxonomy.

    The malformed catalog is injected through the ``data_dir`` override channel
    (issue #33) rather than by assigning the module's cache global, which is the
    unsupported pattern that channel exists to replace.

    The sentinel ``version`` assertion is what keeps that substitution honest: the
    BUNDLED catalog also yields ``{"REFLECTION": 1}`` here, so if the override
    silently fell back to it every assertion below would still pass and the test
    would prove nothing about the dedupe (verified by sabotaging
    ``resolve_data_file`` to ignore ``data_dir`` — it passed).
    """
    import dexllm.capability as cap

    catalog = _catalog()
    catalog["version"] = "dedupe-fixture"
    catalog["entries"][_FOR_NAME]["categories"] = ["REFLECTION", "REFLECTION"]
    (tmp_path / "android_api_map.json").write_text(json.dumps(catalog))

    r = cap.summarize_capabilities(
        _StubDk({_FOR_NAME: ["La/B;->n()V"]}), data_dir=str(tmp_path)
    )
    assert r.catalog_version == "dedupe-fixture", "the override did not take effect"
    assert r.total_call_sites == 1
    assert r.categories == {"REFLECTION": 1}
    assert r.api_hits[0].categories == ["REFLECTION"]


def test_flags_survive_the_sdk_and_mcp_layers():
    """`flags` must traverse raw -> SDK model -> MCP tool dict.

    Each hop is a separate line (`sdk/adapter.py`, `tools.py`) and either was
    individually deletable with a green corpus-less suite before this guard.

    The SDK half calls ``DexKitAdapter.summarize_capabilities`` ITSELF rather than
    re-implementing the conversion: an inline copy asserts what the test does, not
    what the adapter does, and would have kept passing with both adapter lines
    deleted (CI has no corpus, so the APK-backed SDK tests that catch it are
    skipped there). ``__new__`` + ``_dk`` is enough — the method touches nothing
    else, so no real APK load is needed.
    """
    from dexllm.capability import summarize_capabilities
    from dexllm.sdk.adapter import DexKitAdapter

    dk = _StubDk({_GET_DEVICE_ID: ["La/B;->m()V", "La/C;->m()V"]})
    raw = summarize_capabilities(dk)
    assert raw.flags == {"IDENTIFIER": 2}

    adapter = DexKitAdapter.__new__(DexKitAdapter)
    adapter._dk = dk  # type: ignore[attr-defined]
    sdk_report = DexKitAdapter.summarize_capabilities(adapter)
    assert dict(sdk_report.flags) == {"IDENTIFIER": 2}
    assert sdk_report.api_hits[0].flags == ("IDENTIFIER",)

    from dexllm.tools import TOOL_IMPLS

    out = TOOL_IMPLS["summarize_capabilities"](dk)
    assert out["flags"] == {"IDENTIFIER": 2}
    assert out["api_hits"][0]["flags"] == ["IDENTIFIER"]
    assert out["catalog_version"] == raw.catalog_version


def test_by_caller_covers_a_permissionless_api():
    """The caller index must hold callers of APIs that declare no permission.

    `by_caller` was populated INSIDE `for perm in perms:`, so an entry with no
    `permissions` registered no callers at all (dexllm#35) — and that is the
    catalog's behavioural half: 138 of its 263 entries, every REFLECTION /
    PROCESS_EXEC / DYNAMIC_LOAD / NATIVE_CODE / CRYPTO / WEBVIEW / STORAGE API.
    The index covered 26 of the corpus's 634 distinct callers, so "who calls
    `Runtime.exec` here" — the question those entries exist to answer — could not
    be asked of it.

    Corpus-less: `_FOR_NAME` carries no permission and `_GET_DEVICE_ID` does, so
    the stub pins both arms without an APK.
    """
    from dexllm.capability import summarize_capabilities

    dk = _StubDk({_GET_DEVICE_ID: ["La/B;->m()V"], _FOR_NAME: ["La/C;->n()V"]})
    report = summarize_capabilities(dk)

    assert (
        "La/C;->n()V" in report.by_caller
    ), "the caller of a permission-less API is absent from by_caller"
    assert "La/B;->m()V" in report.by_caller


def test_by_caller_values_are_api_signatures():
    """The value is WHICH APIs the caller invokes, not which permissions.

    dexllm#35 chose signatures because they are lossless: the permission and tag
    views are recoverable from the report alone (see the next test), while a
    permission set could not be turned back into an API.
    """
    from dexllm.capability import summarize_capabilities

    dk = _StubDk({_GET_DEVICE_ID: ["La/B;->m()V"], _FOR_NAME: ["La/B;->m()V"]})
    report = summarize_capabilities(dk)

    assert report.by_caller["La/B;->m()V"] == {_GET_DEVICE_ID, _FOR_NAME}


def test_the_permission_view_of_a_caller_is_still_recoverable():
    """The pre-dexllm#35 value must be derivable, or the change lost information.

    This is the join the docstrings hand the reader; it is a guard because the
    field-level half of the argument for signatures over permissions rests on it.
    (The report-level half does NOT: `api_hits` carries `callers`, so either view
    was always derivable from a report — including a pre-fix one. The bug lost no
    data, only the index.)

    The expectation is derived from the CATALOG rather than written out, so adding
    a permission to `getDeviceId` becomes a catalog edit instead of a red test
    blaming the join. It stays discriminating — every by_caller mutant fails it.
    """
    from dexllm.capability import summarize_capabilities

    dk = _StubDk({_GET_DEVICE_ID: ["La/B;->m()V"], _FOR_NAME: ["La/B;->m()V"]})
    report = summarize_capabilities(dk)

    by_api = {h.api_signature: h for h in report.api_hits}
    perms = {p for a in report.by_caller["La/B;->m()V"] for p in by_api[a].permissions}
    expected = set(_entries()[_GET_DEVICE_ID].get("permissions") or ()) | set(
        _entries()[_FOR_NAME].get("permissions") or ()
    )
    assert expected, "the fixture APIs carry no permission — the join proves nothing"
    assert perms == expected


def test_by_caller_is_the_exact_transpose_of_the_hit_callers():
    """Every caller of every matched API appears, and nothing else does.

    The property the nesting bug broke, stated directly rather than as a count —
    a fix that merely moved the line one level out but kept a filter would satisfy
    the tests above on the stub and still under-report on a real APK.
    """
    from dexllm.capability import summarize_capabilities

    dk = _StubDk(
        {
            _GET_DEVICE_ID: ["La/B;->m()V", "La/C;->n()V"],
            _FOR_NAME: ["La/C;->n()V", "La/D;->o()V"],
        }
    )
    report = summarize_capabilities(dk)

    expected: dict = {}
    for hit in report.api_hits:
        for caller in hit.callers:
            expected.setdefault(caller, set()).add(hit.api_signature)
    assert report.by_caller == expected
    assert set(report.by_caller) == {"La/B;->m()V", "La/C;->n()V", "La/D;->o()V"}


def test_by_caller_survives_the_sdk_layer():
    """`sdk/adapter.py` converts each set to a tuple — one deletable line.

    The caller must hold TWO APIs, and the comparison is on sets: with a
    one-API-per-caller stub a reviewer's `tuple(v)[:1]` mutant passed the whole
    suite, and that is not a contrived edit — the field just grew ~25x and
    `tools.py` already justifies omitting it because per-caller sets "can be
    huge", so capping is the natural next change. Comparing as sets also keeps
    this independent of the tuple ORDER, which is only deterministic because the
    adapter sorts.

    The MCP tool deliberately omits `by_caller` (context size), which is why this
    stops at the SDK; that omission is asserted at the end.
    """
    from dexllm.capability import summarize_capabilities
    from dexllm.sdk.adapter import DexKitAdapter

    dk = _StubDk({_FOR_NAME: ["La/C;->n()V"], _GET_DEVICE_ID: ["La/C;->n()V"]})
    raw = summarize_capabilities(dk)
    assert raw.by_caller == {"La/C;->n()V": {_FOR_NAME, _GET_DEVICE_ID}}

    adapter = DexKitAdapter.__new__(DexKitAdapter)
    adapter._dk = dk  # type: ignore[attr-defined]
    sdk_report = DexKitAdapter.summarize_capabilities(adapter)
    assert {k: set(v) for k, v in sdk_report.by_caller.items()} == {
        "La/C;->n()V": {_FOR_NAME, _GET_DEVICE_ID}
    }

    from dexllm.tools import TOOL_IMPLS

    # NON-DISCRIMINATING BY DESIGN on the fix itself: it pins the documented
    # omission, so a later change that starts emitting the (now much larger)
    # caller index into an LLM context is a conscious edit, not a slip.
    assert "by_caller" not in TOOL_IMPLS["summarize_capabilities"](dk)


def test_the_sdk_orders_the_caller_index_deterministically():
    """A `set` -> `tuple` conversion must sort, or the order varies per process.

    `PYTHONHASHSEED` randomises string hashing, so `tuple(some_set)` differs
    between runs. This repo gates cross-process byte-identity elsewhere, and the
    change made multi-valued entries common (they were rare when the values were
    permissions), so the exposure went from a corner case to the normal one.

    MANY on BOTH axes, deliberately: with two elements an unsorted `tuple(set)`
    lands in sorted order half the time, so the first cut of this guard let the
    mutant through on the seed it happened to run under — and with one caller per
    API the `callers` half was trivially sorted, so its mutant survived every seed.
    At n=8..10 the unsorted variant agrees with `sorted` in 1 of n! orders, which
    is deterministic in every sense that matters; verified against both mutants on
    five `PYTHONHASHSEED` values.
    """
    from dexllm.sdk.adapter import DexKitAdapter

    many = list(_entries())[:10]
    callers = [f"La/C{i};->n()V" for i in range(8)]
    assert len(many) >= 8, "catalog too small to make the order check discriminating"
    dk = _StubDk({sig: callers for sig in many})
    adapter = DexKitAdapter.__new__(DexKitAdapter)
    adapter._dk = dk  # type: ignore[attr-defined]
    report = DexKitAdapter.summarize_capabilities(adapter)

    assert set(report.by_caller) == set(callers)
    for values in report.by_caller.values():
        assert values == tuple(sorted(values))
        assert set(values) == set(many)
    for hit in report.api_hits:
        assert hit.callers == tuple(sorted(hit.callers))
        assert set(hit.callers) == set(callers)


def test_the_caller_index_does_not_depend_on_the_tag_axes_either(tmp_path):
    """An entry with NEITHER permissions NOR categories must still index.

    The same defect shape as dexllm#35 one axis over: nesting the line in
    `for cat in cats:` passes every other guard, because every BUNDLED entry
    carries a category. A replacement catalog need not — `_validate_catalog`
    requires the tag lists to be lists, not to be non-empty, and the module
    docstring only says an entry "should" have one. So the override path, which is
    a supported feature, could silently reproduce the bug.
    """
    from dexllm.capability import summarize_capabilities

    bare = "Lp/Q;->r()V"
    (tmp_path / "android_api_map.json").write_text(
        json.dumps(
            {
                "version": "test",
                "category_vocabulary": ["REFLECTION"],
                "flag_vocabulary": [],
                "entries": {bare: {"permissions": [], "categories": [], "flags": []}},
            }
        )
    )
    dk = _StubDk({bare: ["La/Z;->z()V"]})
    report = summarize_capabilities(dk, data_dir=tmp_path)

    assert report.by_caller == {"La/Z;->z()V": {bare}}


def test_relocating_the_caller_index_left_the_counters_alone():
    """The half the a/b covered and the suite did not.

    dexllm#35 moved one statement out of `for perm in perms:`; nothing else in the
    loop changed. A future refactor that gets the caller index right while
    disturbing a counter would pass every test above.
    """
    from dexllm.capability import summarize_capabilities

    dk = _StubDk(
        {
            _GET_DEVICE_ID: ["La/B;->m()V", "La/C;->n()V"],
            _FOR_NAME: ["La/C;->n()V"],
        }
    )
    report = summarize_capabilities(dk)

    # Expected counts come from the CATALOG, not from a literal: the permissions on
    # `getDeviceId` are derived from AOSP and have already changed once
    # (READ_PRIVILEGED_PHONE_STATE joined READ_PHONE_STATE when the catalog stopped
    # hand-typing them). What this test is about is the ARITHMETIC — 2 call sites
    # times whatever the entry carries — so pinning the values would make it a
    # catalog test that goes red on an unrelated data refresh.
    entry = _entries()[_GET_DEVICE_ID]
    assert entry["permissions"] and entry["flags"] == ["IDENTIFIER"], _GET_DEVICE_ID
    assert report.total_call_sites == 3
    assert report.permissions == {p: 2 for p in entry["permissions"]}
    assert report.categories == {"TELEPHONY": 2, "REFLECTION": 1}
    assert report.flags == {"IDENTIFIER": 2}


def test_every_indexed_signature_is_a_key_of_the_report_s_own_hits():
    """Join totality as a PROPERTY, so the documented recipe cannot KeyError.

    `test_the_permission_view_of_a_caller_is_still_recoverable` exercises the join
    on one caller of a two-API stub, so it would survive an unmatched signature
    leaking into the index; this states the invariant instead.
    """
    from dexllm.capability import summarize_capabilities

    dk = _StubDk({_GET_DEVICE_ID: ["La/B;->m()V"], _FOR_NAME: ["La/C;->n()V"]})
    report = summarize_capabilities(dk)

    indexed = set().union(*report.by_caller.values())
    assert indexed <= {h.api_signature for h in report.api_hits}
    assert indexed == {_GET_DEVICE_ID, _FOR_NAME}


def test_only_categories_filters_the_caller_index_with_the_hits():
    """What makes the documented join well-defined per report.

    `only_categories` `continue`s before both `by_caller` and `api_hits` are
    written, so the two stay the same subset. Pre-dexllm#35 this was vacuous for a
    permission-less filter like REFLECTION — the index was empty either way — so it
    is newly observable behaviour with nothing pinning it.
    """
    from dexllm.capability import summarize_capabilities

    dk = _StubDk({_GET_DEVICE_ID: ["La/B;->m()V"], _FOR_NAME: ["La/B;->m()V"]})
    report = summarize_capabilities(dk, only_categories={"REFLECTION"})

    assert report.by_caller == {"La/B;->m()V": {_FOR_NAME}}
    assert {h.api_signature for h in report.api_hits} == {_FOR_NAME}


# --- dexllm#36: FIELD-descriptor keys -----------------------------------------

_FIELD_KEYS = {
    "Landroid/provider/ContactsContract$Contacts;->CONTENT_URI:Landroid/net/Uri;": (
        "ContactsContract.java",
        ["Contacts"],
    ),
    "Landroid/provider/ContactsContract$CommonDataKinds$Phone;"
    "->CONTENT_URI:Landroid/net/Uri;": (
        "ContactsContract.java",
        ["CommonDataKinds", "Phone"],
    ),
    "Landroid/provider/CallLog$Calls;->CONTENT_URI:Landroid/net/Uri;": (
        "CallLog.java",
        ["Calls"],
    ),
    "Landroid/provider/CalendarContract$Events;->CONTENT_URI:Landroid/net/Uri;": (
        "CalendarContract.java",
        ["Events"],
    ),
}


def test_a_field_key_resolves_through_the_field_lookup(write_catalog):
    """The dispatch itself: a field key must NOT go to `find_call_sites_to`.

    That is the whole defect — `ParseApiDescriptor` requires a `(` after `->`, so
    a field descriptor matched nothing on every possible input and raised nothing.
    Three entries shipped that way for 15 months.
    """
    field_key = next(iter(_FIELD_KEYS))
    catalog = {
        "version": "t",
        "category_vocabulary": ["CONTACTS"],
        "flag_vocabulary": [],
        "entries": {field_key: {"categories": ["CONTACTS"]}},
    }

    class _Dk:
        def find_call_sites_to(self, descriptor):
            raise AssertionError(f"a FIELD key went to the method lookup: {descriptor}")

        def find_methods_reading_field(self, descriptor):
            return ["La/B;->m()V", "La/C;->n()V"] if descriptor == field_key else []

    rep = capability.summarize_capabilities(_Dk(), data_dir=write_catalog(catalog))
    assert rep.matched_apis == 1
    hit = rep.api_hits[0]
    assert hit.field_access_count == 2
    assert hit.call_site_count == 0, "a field entry must not claim invoke sites"
    assert rep.total_field_accesses == 2 and rep.total_call_sites == 0
    assert rep.categories == {"CONTACTS": 2}
    assert set(rep.by_caller) == {"La/B;->m()V", "La/C;->n()V"}


def test_the_two_counters_are_never_summed_into_one(write_catalog):
    """`call_site_count` keeps EXACTLY its released meaning (dexllm#36).

    Widening it to "places that touch the API" needs no type or name change, so a
    consumer would read a different number with nothing to warn them — the quiet
    break dexllm#35 was. This pins the split in a report holding both forms.
    """
    field_key = next(iter(_FIELD_KEYS))
    catalog = {
        "version": "t",
        "category_vocabulary": ["CONTACTS", "REFLECTION"],
        "flag_vocabulary": [],
        "entries": {
            field_key: {"categories": ["CONTACTS"]},
            _FOR_NAME: {"categories": ["REFLECTION"]},
        },
    }

    class _Dk:
        def find_call_sites_to(self, descriptor):
            return [_Site("La/B;->m()V")] if descriptor == _FOR_NAME else []

        def find_methods_reading_field(self, descriptor):
            return ["La/C;->n()V", "La/D;->o()V"] if descriptor == field_key else []

    rep = capability.summarize_capabilities(_Dk(), data_dir=write_catalog(catalog))
    by_sig = {h.api_signature: h for h in rep.api_hits}
    assert by_sig[_FOR_NAME].call_site_count == 1
    assert by_sig[_FOR_NAME].field_access_count == 0
    assert by_sig[field_key].field_access_count == 2
    assert by_sig[field_key].call_site_count == 0
    # the two totals stay apart, and neither absorbs the other
    assert rep.total_call_sites == 1 and rep.total_field_accesses == 2
    # …while the tag Counters DO count both, which is the documented asymmetry
    assert rep.categories == {"REFLECTION": 1, "CONTACTS": 2}


def test_field_counts_reach_the_sdk_and_mcp_layers(write_catalog, monkeypatch):
    """A counter nothing propagates is a counter nobody can read."""
    field_key = next(iter(_FIELD_KEYS))
    catalog = {
        "version": "t",
        "category_vocabulary": ["CONTACTS"],
        "flag_vocabulary": [],
        "entries": {field_key: {"categories": ["CONTACTS"]}},
    }

    class _Dk:
        def find_call_sites_to(self, descriptor):
            return []

        def find_methods_reading_field(self, descriptor):
            return ["La/B;->m()V"] if descriptor == field_key else []

    from dexllm import datadir, tools
    from dexllm.sdk.adapter import DexKitAdapter

    # monkeypatch, per conftest's own stated rule — the first cut mutated
    # os.environ directly and was contained only by an autouse fixture it does
    # not use.
    monkeypatch.setenv(datadir.ENV_VAR, write_catalog(catalog))
    datadir.clear_data_caches()

    # …through the adapter's real method, not a private converter: the point is
    # that the value survives the layer a consumer actually calls.
    model = DexKitAdapter.summarize_capabilities(type("_A", (), {"_dk": _Dk()})())
    assert model.api_hits[0].field_access_count == 1
    # …and the REPORT-level total, which docs/sdk.md documents. It was missing
    # from the SDK model in the first cut while the docs already asserted the
    # inequality that needs it — "a counter nothing propagates is a counter
    # nobody can read" applied to the very test that says so.
    assert model.total_field_accesses == 1
    assert sum(model.categories.values()) >= (
        model.total_call_sites + model.total_field_accesses
    )

    out = tools.execute("summarize_capabilities", {}, _Dk())
    assert out["total_field_accesses"] == 1
    assert out["api_hits"][0]["field_accesses"] == 1
    assert out["api_hits"][0]["call_sites"] == 0


def test_the_bundled_field_keys_name_real_aosp_fields():
    """A typo'd key matches nothing and raises nothing — the #36 failure itself.

    Shape guards cannot catch `CONTENT_URl` or a wrong nesting, and the bundled
    corpus references no `CONTENT_URI` at all (measured: 0), so nothing else here
    can. Checked against a local AOSP checkout; SKIPS without one, since that is
    an environment fact (CI has none).
    """
    import os
    import re

    root = pathlib.Path(
        os.environ.get("DEXLLM_AOSP_SRC", pathlib.Path.home() / "Project" / "aosp")
    )
    provider = root / "frameworks/base/core/java/android/provider"
    if not provider.is_dir():
        pytest.skip(f"no AOSP checkout at {root} (set $DEXLLM_AOSP_SRC)")

    for key, (fname, nesting) in _FIELD_KEYS.items():
        assert key in _entries(), f"{key} is not in the bundled catalog"
        member = key.partition(";->")[2]
        name, _, ftype = member.partition(":")
        body = (provider / fname).read_text()
        for cls in nesting:  # walk into the nested class by brace matching
            m = re.search(rf"\b(?:class|interface)\s+{cls}\b[^{{]*\{{", body)
            assert m, f"{fname}: no class {cls} for {key}"
            i = m.end() - 1
            depth = 0
            for j in range(i, len(body)):
                depth += body[j] == "{"
                depth -= body[j] == "}"
                if depth == 0:
                    break
            body = body[i + 1 : j]
        assert re.search(
            rf"public\s+static\s+final\s+Uri\s+{name}\s*=", body
        ), f"{key}: {'.'.join(nesting)} declares no `public static final Uri {name}`"
        assert ftype == "Landroid/net/Uri;", key


def test_the_documented_counter_inequality_holds_with_both_key_forms(write_catalog):
    """`sum(categories) >= total_call_sites + total_field_accesses` (dexllm#36).

    docs/usage.md, docs/api.md and docs/sdk.md all assert this. It used to read
    `>= total_call_sites` alone, which a matched FIELD entry falsifies: the
    Counters count TOUCHES of either kind while the two totals keep the units
    apart, so a field access lands on the left and not on the right.
    """
    field_key = next(iter(_FIELD_KEYS))
    catalog = {
        "version": "t",
        "category_vocabulary": ["CONTACTS", "REFLECTION"],
        "flag_vocabulary": [],
        "entries": {
            field_key: {"categories": ["CONTACTS"]},
            _FOR_NAME: {"categories": ["REFLECTION"]},
        },
    }

    class _Dk:
        def find_call_sites_to(self, descriptor):
            return [_Site("La/B;->m()V")] if descriptor == _FOR_NAME else []

        def find_methods_reading_field(self, descriptor):
            return ["La/C;->n()V", "La/D;->o()V"] if descriptor == field_key else []

    rep = capability.summarize_capabilities(_Dk(), data_dir=write_catalog(catalog))
    total = rep.total_call_sites + rep.total_field_accesses
    assert sum(rep.categories.values()) >= total
    # …and equality holds here, since every entry carries exactly one tag — which
    # is what makes the field half genuinely load-bearing rather than slack
    assert sum(rep.categories.values()) == total == 3
    # the OLD wording would be false on this very report
    assert sum(rep.categories.values()) > rep.total_call_sites


def test_a_field_entry_matches_on_a_REAL_dex(dk):
    """The gap that let the 15-month bug ship again, one layer down.

    Every other field test drives a stub, so none of them could see that
    `find_methods_reading_field` resolved nothing for a FRAMEWORK class: it began
    with `LocateClassDex`, which answers only for a class DECLARED in a loaded
    dex. So dexllm#36's first cut swapped one always-empty lookup for another and
    the four `CONTENT_URI` entries were inert on every possible input — the very
    defect the issue is about. Two reviewers found it; no test could.

    This asserts the primitive against the real binding, corpus-independently: any
    field the app provably reads must resolve to at least one reader.
    """
    fields = dk.list_fields()
    # A FRAMEWORK field — the case that was broken. `SDK_INT` is read by
    # essentially every Android app and its class is never declared in the APK.
    sdk_int = "Landroid/os/Build$VERSION;->SDK_INT:I"
    require_corpus_shape(
        sdk_int in fields,
        "reference to Build.VERSION.SDK_INT",
        "the corpus stopped carrying the most universal framework field read",
    )
    assert dk.locate_class_dex("Landroid/os/Build$VERSION;") == -1, (
        "premise: the declaring class is NOT in the app, which is exactly what "
        "the old lookup required"
    )
    readers = dk.find_methods_reading_field(sdk_int)
    assert readers, "a framework field the app reads must resolve to its readers"
    assert all(";->" in r for r in readers)


def test_field_access_count_is_per_instruction_not_per_method(write_catalog):
    """Pins the UNIT, which the stubs cannot (dexllm#36).

    `find_methods_reading_field` is documented as NOT deduplicated — one entry per
    read instruction — but every field stub returned DISTINCT method descriptors,
    so a mutant applying `dict.fromkeys` (i.e. making the code match an earlier,
    wrong docstring that said "reading methods") survived the entire suite. Both
    counters are the same unit, which is why summing them is meaningful and why
    `field_access_count` is NOT `len(callers)`.
    """
    field_key = next(iter(_FIELD_KEYS))
    catalog = {
        "version": "t",
        "category_vocabulary": ["CONTACTS"],
        "flag_vocabulary": [],
        "entries": {field_key: {"categories": ["CONTACTS"]}},
    }

    class _Dk:
        def find_call_sites_to(self, descriptor):
            return []

        def find_methods_reading_field(self, descriptor):
            # ONE method, TWO read instructions — what the real binding returns
            return ["La/B;->m()V", "La/B;->m()V"] if descriptor == field_key else []

    rep = capability.summarize_capabilities(_Dk(), data_dir=write_catalog(catalog))
    hit = rep.api_hits[0]
    assert hit.field_access_count == 2, "instructions, not methods"
    assert len(hit.callers) == 1, "…while `callers` is a set, so they differ"
    assert rep.total_field_accesses == 2
    assert rep.categories == {"CONTACTS": 2}, "the Counter follows the instructions"


def test_the_mcp_ranking_counts_field_accesses(write_catalog, monkeypatch):
    """A field entry must be able to outrank a method one.

    The sort key changed to touches; nothing asserted it, so reverting it to
    `call_site_count` alone — which sinks every field entry to the bottom with a 0
    it is not supposed to have — survived the whole suite.
    """
    field_key = next(iter(_FIELD_KEYS))
    catalog = {
        "version": "t",
        "category_vocabulary": ["CONTACTS", "REFLECTION"],
        "flag_vocabulary": [],
        "entries": {
            field_key: {"categories": ["CONTACTS"]},
            _FOR_NAME: {"categories": ["REFLECTION"]},
        },
    }

    class _Dk:
        def find_call_sites_to(self, descriptor):
            return [_Site("La/B;->m()V")] if descriptor == _FOR_NAME else []

        def find_methods_reading_field(self, descriptor):
            return ["La/C;->n()V"] * 5 if descriptor == field_key else []

    from dexllm import datadir, tools

    monkeypatch.setenv(datadir.ENV_VAR, write_catalog(catalog))
    datadir.clear_data_caches()
    out = tools.execute("summarize_capabilities", {}, _Dk())
    assert [h["api"] for h in out["api_hits"]] == [
        field_key,
        _FOR_NAME,
    ], "5 field accesses must outrank 1 call site"


def test_the_ranking_is_a_total_order(write_catalog, monkeypatch):
    """Ties break on the signature, so catalog ORDER cannot move the ranking.

    `sorted` is stable, so the ranking followed `entries` iteration order — and
    re-serialising the catalog (as dexllm#36 did) reordered the MCP `top_apis` on
    16 of 32 corpus sources with no count changing.
    """
    keys = [_FOR_NAME, _GET_DEVICE_ID]
    base = {
        "version": "t",
        "category_vocabulary": ["REFLECTION", "TELEPHONY"],
        "flag_vocabulary": [],
    }
    meta = {
        _FOR_NAME: {"categories": ["REFLECTION"]},
        _GET_DEVICE_ID: {"categories": ["TELEPHONY"]},
    }

    class _Dk:  # equal counts, so only the tie-break can order them
        def find_call_sites_to(self, descriptor):
            return [_Site("La/B;->m()V")] if descriptor in meta else []

        def find_methods_reading_field(self, descriptor):
            return []

    from dexllm import datadir, tools

    seen = []
    for order in (keys, list(reversed(keys))):
        catalog = {**base, "entries": {k: meta[k] for k in order}}
        monkeypatch.setenv(datadir.ENV_VAR, write_catalog(catalog))
        datadir.clear_data_caches()
        seen.append(
            [
                h["api"]
                for h in tools.execute("summarize_capabilities", {}, _Dk())["api_hits"]
            ]
        )
    assert (
        seen[0] == seen[1] == sorted(keys)
    ), f"the ranking followed catalog order: {seen}"


def test_is_field_key_routes_a_malformed_key_to_the_field_lookup():
    """Pins the documented routing of a third shape.

    `_is_field_key`'s docstring reasons about malformed keys ("routes to a lookup
    that returns nothing"), so WHICH lookup is stated behaviour — and a mutant
    sending a key with no `;->` to the METHOD lookup survived the suite. Both
    lookups are silent on such input, so the cost is only which one is asked; the
    point is that the answer is pinned rather than incidental.
    """
    from dexllm.capability import _is_field_key

    for method_key in (
        _FOR_NAME,
        "Lcls;-><init>()V",
        "Lcls;->m(Ljava/lang/String;I)Ljava/lang/Object;",
    ):
        assert not _is_field_key(method_key), method_key
    for field_or_malformed in (
        "Lcls;->NAME:Ltype;",
        "Lcls;->NAME:[I",
        "",
        "garbage",
        "Lcls;",
        "Lcls;->",
    ):
        assert _is_field_key(field_or_malformed), field_or_malformed


# --- dexllm#30: the catalog is generated, and the selection is a decision ------
#
# The enrichment moved the catalog from 50 hand-typed entries to 276 generated from
# a curated (class, member) selection. Three things now have to be guarded that a
# schema check cannot see: that the committed file still IS what the generator
# produces, that every key names a real AOSP member (a typo matches nothing and
# raises nothing — the dexllm#36 defect), and that the two selection rules the
# measurements forced are not quietly reversed by a later bulk load.

_GENERATOR = (
    pathlib.Path(__file__).resolve().parents[1]
    / "scripts"
    / "gen_capability_catalog.py"
)

# APIs excluded BY MEASUREMENT, not by taste. Most were top additions of the
# rejected full projection (`startActivity` / `query` / `startActivityForResult` in
# 16 of the 32 corpus sources each); the reflection mechanics and
# `NotificationManager.notify` carry no `@RequiresPermission` at all and so could
# never arrive that way — they are here because they are equally ubiquitous and the
# rule has to be one rule. The exhaustive permission surface is
# `dangerous_permission_apis`, which has all 5,150.
# Matched on the MEMBER part, not on a full key prefix: the catalog's own rule is
# that a key names the class the APP writes, so `Landroid/app/Activity;->startActivity`
# is as legitimate a spelling as the `Context` one — and a receiver-specific prefix
# list would wave it through (it occurs in 15 of the 32 corpus sources).
_UBIQUITOUS = (
    "->startActivity(",
    "->startActivities(",
    "->startActivityForResult(",
    "->sendBroadcast(",
    "->sendOrderedBroadcast(",
    "->bindService(",
    "->getSystemService(",
    "Landroid/content/ContentResolver;->query(",
    "Landroid/content/pm/PackageManager;->getPackageInfo(",
    "Landroid/app/NotificationManager;->notify(",
    # the reflection MECHANICS, as opposed to the intent-expressing steps that ARE
    # listed (forName / invoke / setAccessible / loadClass): including these tripled
    # REFLECTION on the corpus while identifying no app the kept entries do not.
    "Ljava/lang/Class;->getDeclaredMethod(",
    "Ljava/lang/Class;->getMethod(",
    "Ljava/lang/Class;->getDeclaredField(",
    "Ljava/lang/Class;->newInstance(",
    "Ljava/lang/reflect/Field;->get(",
    "Ljava/lang/reflect/Field;->set(",
)


def _dataset_root():
    import os

    root = pathlib.Path(
        os.environ.get(
            "DEXLLM_AOSP_DATASET", pathlib.Path.home() / "Project" / "aosp_data_set"
        )
    )
    if not (root / "aosp_members.csv").is_file():
        pytest.skip(f"no aosp_data_set at {root} (set $DEXLLM_AOSP_DATASET)")
    return root


def _generator():
    import importlib.util

    spec = importlib.util.spec_from_file_location("gen_capability_catalog", _GENERATOR)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_the_committed_catalog_is_what_the_generator_produces():
    """Otherwise "generated" is a claim about history, not about this file.

    A hand-edit to the JSON would survive every other guard here and then be
    silently reverted by the next regeneration. Comparing the parsed objects (not
    the bytes — key order and indentation are not the contract) is what makes the
    script the source of truth.

    Needs the AOSP dataset, so it SKIPS in CI, and so does every other guard that
    re-runs the generator. `test_the_catalog_entries_match_their_pinned_digest`
    below is the one that holds without it.
    """
    module = _generator()
    built = module.build(_dataset_root())
    assert built == _catalog(), (
        "src/dexllm/data/android_api_map.json differs from "
        "scripts/gen_capability_catalog.py's output — re-run the generator "
        "(edit CURATED, not the JSON)"
    )


def test_every_catalog_key_names_a_real_aosp_member():
    """A key that names nothing matches nothing, forever, and raises nothing.

    Three field keys shipped dead for three months that way (dexllm#36). The
    generator resolves names rather than accepting descriptors, so this should be
    unreachable — which is exactly why it is worth asserting: it checks the RESULT,
    not the intent, and it also pins the receiver-vs-declaring-class rule
    (`Method;->setAccessible` is legal here although AOSP declares it on
    `AccessibleObject`, because that is the spelling a dex records).

    The WHOLE descriptor is compared, not the owner and member name: an earlier cut
    checked only those two and so passed a key with a fabricated parameter list or a
    wrong return type — the same silently-dead outcome, one field along.
    """
    module = _generator()
    built = module.build(_dataset_root())["entries"]
    unknown = sorted(set(_entries()) - set(built))
    assert not unknown, (
        "these keys do not correspond to any AOSP member the generator can resolve "
        f"from a curated name: {unknown}"
    )


def test_no_ubiquitous_api_is_in_the_catalog():
    """The measured selection rule, pinned so a bulk load cannot silently undo it.

    Each prefix below was actually matched by the rejected full projection on the
    bundled corpus. They are not absent because nobody thought of them — several
    carry a permission and would arrive with any `@RequiresPermission` import.
    """
    offenders = sorted(k for k in _entries() for p in _UBIQUITOUS if p in k)
    assert not offenders, (
        "these APIs are excluded by measurement (they match in essentially every "
        f"app); use dangerous_permission_apis for the full surface: {offenders}"
    )


# The catalog's content, pinned WITHOUT the AOSP dataset. Everything above that
# re-runs the generator SKIPS in CI, so before this existed a hand-edit to the JSON
# — a fabricated parameter list, a typo'd member, a wrong field type, a deleted
# entry, an added ubiquitous API — shipped green: 7 of 8 such mutants passed a
# dataset-less run. Update BOTH numbers when the catalog legitimately changes; that
# edit is the point, since it is what makes a catalog change a conscious one rather
# than a diff nobody has to look at.
CATALOG_ENTRY_COUNT = 263
CATALOG_ENTRY_DIGEST = (
    "90377ef7c35a39d8e32b423028d8d78ba54f362d1cb072bc97e30581f88c2072"
)


def test_the_catalog_entries_match_their_pinned_digest():
    """The only content guard that survives a run without the AOSP dataset."""
    import hashlib

    entries = _entries()
    digest = hashlib.sha256(
        json.dumps(entries, sort_keys=True, separators=(",", ":")).encode()
    ).hexdigest()
    assert len(entries) == CATALOG_ENTRY_COUNT, (
        f"the catalog has {len(entries)} entries, pinned at {CATALOG_ENTRY_COUNT} — "
        "re-run scripts/gen_capability_catalog.py and update the pin"
    )
    assert digest == CATALOG_ENTRY_DIGEST, (
        "the catalog's entries changed; regenerate with "
        "scripts/gen_capability_catalog.py and update CATALOG_ENTRY_DIGEST to "
        f"{digest}"
    )


# ── dexllm#49: a bundled library's call sites are not the app's ───────────────
#
# Corpus-less by construction (`_StubDk`), which is what makes these run in the
# CI leg that has no APKs and under a `$DEXLLM_TEST_APK` narrowing alike — the
# behaviour is a property of the code, not of any sample.

from dexllm._callers import (  # noqa: E402
    _FRAMEWORK_CALLER_PREFIXES,
    _is_framework_caller,
)

_LIB_CALLER = "Landroidx/core/app/ActivityCompat;->requestPermissions()V"
_LIB_CALLER2 = "Lkotlin/io/FilesKt;->copyTo()V"
_APP_CALLER = "Lcom/example/app/Main;->run()V"


def test_library_callers_are_dropped_by_default():
    """The default report counts the APP's call sites, not the ones it bundles.

    Per TOUCH, not per API: the register of callers mixes both kinds (18 of
    tvleanback's 20 `Class.forName` sites are androidx), so a variant that keeps
    an API whole as soon as ONE app caller exists would still count the 18. This
    fixture makes that variant fail — 2 library touches and 1 app touch on the
    SAME api.
    """
    from dexllm.capability import summarize_capabilities

    dk = _StubDk({_FOR_NAME: [_LIB_CALLER, _APP_CALLER, _LIB_CALLER2]})

    app = summarize_capabilities(dk)
    assert app.matched_apis == 1
    assert app.total_call_sites == 1
    assert app.api_hits[0].call_site_count == 1
    assert app.api_hits[0].callers == {_APP_CALLER}
    assert app.categories["REFLECTION"] == 1
    assert set(app.by_caller) == {_APP_CALLER}

    every = summarize_capabilities(dk, app_only=False)
    assert every.total_call_sites == 3
    assert every.api_hits[0].call_site_count == 3
    assert every.api_hits[0].callers == {_LIB_CALLER, _APP_CALLER, _LIB_CALLER2}
    assert every.categories["REFLECTION"] == 3
    assert set(every.by_caller) == {_LIB_CALLER, _APP_CALLER, _LIB_CALLER2}


def test_an_api_only_libraries_call_leaves_the_report_entirely():
    """A library-only API is DROPPED, not reported with a zero count.

    `BIOMETRIC` fires wherever `FingerprintManagerCompat` is bundled at all — 100%
    of the corpus's touches — so "the report no longer says this" is the intended
    outcome, and it has to reach `matched_apis` / `api_hits` / the Counters, not
    just the totals. Filtering AFTER the emptiness check would leave a hit behind
    with BOTH counters 0 — and `tools.py` ranks by
    `-(call_site_count + field_access_count)`, whose maximum is 0, so every such
    phantom sorts to the TOP of `top_apis`, ahead of every real hit.
    """
    from dexllm.capability import summarize_capabilities

    dk = _StubDk({_GET_DEVICE_ID: [_LIB_CALLER]})

    app = summarize_capabilities(dk)
    assert app.matched_apis == 0
    assert app.api_hits == []
    assert app.total_call_sites == 0
    assert app.by_caller == {}
    assert not app.categories and not app.permissions and not app.flags

    assert summarize_capabilities(dk, app_only=False).matched_apis == 1


def test_the_field_lookup_is_filtered_too():
    """A FIELD key resolves to READING METHODS, which are callers just the same.

    The two key forms take different lookups (dexllm#36), so a filter applied on
    only the invoke branch would leave every `CONTENT_URI` entry unfiltered — and
    that branch is the one whose result is not a `CallSite` object, so it is the
    easy one to miss.
    """
    from dexllm.capability import summarize_capabilities

    # A literal from `_FIELD_KEYS`, the set this file already pins, rather than a
    # `next()` over the live catalog — which raises StopIteration (an ERROR, not
    # an explanation) the day the catalog carries no field key. `_StubDk` answers
    # from whatever key it is handed, so the key need not be IN the catalog for
    # the lookup to be exercised; it only has to be one the shape dispatch routes
    # to `find_methods_reading_field`, and this file asserts that separately.
    field_key = sorted(_FIELD_KEYS)[0]
    assert "(" not in field_key.partition(";->")[2], "not a field-shaped key"
    dk = _StubDk({}, {field_key: [_LIB_CALLER, _APP_CALLER]})

    app = summarize_capabilities(dk)
    assert app.total_field_accesses == 1
    assert app.api_hits[0].field_access_count == 1
    assert app.api_hits[0].callers == {_APP_CALLER}
    assert summarize_capabilities(dk, app_only=False).total_field_accesses == 2


def test_both_apis_share_one_library_predicate():
    """dexllm#49: ONE definition of "a bundled library", not two that agree today.

    The issue's third open question. A copied prefix tuple would pass every other
    test in this file and drift on the first edit, so the guard is object
    identity, not equal behaviour on a sample of descriptors.
    """
    import dexllm.capability as cap
    import dexllm.dangerous_api as dang
    from dexllm._callers import _FRAMEWORK_CALLER_PREFIXES, _is_framework_caller

    assert cap._is_framework_caller is _is_framework_caller
    assert dang._is_framework_caller is _is_framework_caller
    assert dang._FRAMEWORK_CALLER_PREFIXES is _FRAMEWORK_CALLER_PREFIXES


def test_the_mcp_tool_forwards_app_only_and_says_which_mode_it_ran():
    """The tool omits the per-caller sets, so the mode must be readable elsewhere.

    Without the echoed key a model comparing two sessions' counts cannot tell it
    was comparing two MODES — and `by_caller` / `callers`, which would otherwise
    reveal it, are deliberately not in this payload.
    """
    from dexllm import tools

    dk = _StubDk({_FOR_NAME: [_LIB_CALLER, _APP_CALLER]})

    app = tools.execute("summarize_capabilities", {}, dk)
    assert app["app_only"] is True
    assert app["total_call_sites"] == 1
    assert app["matched_apis"] == 1

    every = tools.execute("summarize_capabilities", {"app_only": False}, dk)
    assert every["app_only"] is False
    assert every["total_call_sites"] == 2


def test_the_sdk_adapter_forwards_app_only(monkeypatch):
    """The port declares the knob; the adapter must actually pass it on.

    An adapter that accepts `app_only` and drops it type-checks, satisfies the
    Protocol (which carries no runtime signature conformance) and passes the
    argument-name audits — it is only wrong in the value it returns. Driven by a
    recording double rather than a corpus, so it holds with no APKs present.

    The double also SYNTHESISES a mode-dependent report, so the assertion is on
    the value that comes BACK, not only on the argument that went in: watching
    the argument alone would pass an adapter that forwarded correctly and then
    rebuilt a field from a second, unfiltered call. The bundled
    `tests/data/multidex.apk` matches no catalog API, so a real report would make
    both modes an identical empty one and the value check vacuous.
    """
    import dexllm
    from dexllm.sdk.adapter import DexKitAdapter

    seen = []

    def spy(dk, **kw):
        mode = kw.get("app_only", "ABSENT")
        seen.append(mode)
        return capability.CapabilityReport(
            permissions=Counter({"P": 1 if mode else 9}),
            categories=Counter({"C": 1 if mode else 9}),
            flags=Counter(),
            by_caller=(
                {_APP_CALLER: {_FOR_NAME}}
                if mode
                else {_APP_CALLER: {_FOR_NAME}, _LIB_CALLER: {_FOR_NAME}}
            ),
            api_hits=[
                capability.ApiHit(
                    api_signature=_FOR_NAME,
                    permissions=["P"],
                    categories=["C"],
                    call_site_count=1 if mode else 9,
                    callers={_APP_CALLER} if mode else {_APP_CALLER, _LIB_CALLER},
                )
            ],
            total_call_sites=1 if mode else 9,
            catalog_version="t",
            catalog_size=1,
            matched_apis=1,
            dropped_touches=8 if mode else 0,
            dropped_apis=3 if mode else 0,
        )

    monkeypatch.setattr(dexllm, "summarize_capabilities", spy)

    session = DexKitAdapter(
        str(pathlib.Path(__file__).parent / "data" / "multidex.apk")
    )
    app = session.summarize_capabilities()
    every = session.summarize_capabilities(app_only=False)

    for report, sites, dropped, callers in (
        (app, 1, (8, 3), 1),
        (every, 9, (0, 0), 2),
    ):
        assert report.total_call_sites == sites
        assert report.categories["C"] == sites
        assert report.permissions["P"] == sites
        assert report.api_hits[0].call_site_count == sites
        assert len(report.api_hits[0].callers) == callers
        assert len(report.by_caller) == callers
        assert (report.dropped_touches, report.dropped_apis) == dropped
    assert seen == [True, False], f"the adapter did not forward app_only: {seen}"


# The shared tuple's CONTENT, PINNED — the same device (and the same reason) as
# `CATEGORY_VOCABULARY` above: changing it must be a conscious edit in two places.
# The parametrised guard below iterates the tuple ITSELF, so it is blind to an
# EDIT of the tuple by construction — deleting `"Lcom/google/android/"` (69 corpus
# touches) merely removes a case, and it survived the whole suite until this pin
# existed. The only other content assertions in the repo are in
# tests/test_dangerous_api.py, which is corpus-gated and therefore skips in the CI
# leg with no APKs; this one is corpus-less. Five of the eleven have ZERO weight
# on the bundled corpus, so no a/b can catch them moving either.
LIBRARY_CALLER_PREFIXES = (
    "Landroidx/",
    "Landroid/support/",
    "Landroid/arch/",
    "Lkotlin/",
    "Lkotlinx/",
    "Ljava/",
    "Ljavax/",
    "Ldalvik/",
    "Lcom/google/android/",
    "Lcom/google/common/",
    "Lcom/google/gson/",
)


def test_the_library_prefix_tuple_matches_its_pin():
    """Adding or removing a prefix is a two-place edit, not a one-line diff.

    It decides the DEFAULT value of six released `CapabilityReport` fields since
    dexllm#49, and of `dangerous_permission_api_callers`' rows before that — so a
    silent edit changes what two public APIs report with nothing objecting.
    ORDER is pinned too: it is a `str.startswith` argument, so order does not
    affect behaviour, but an unordered comparison would hide a reordering that
    makes the two lists harder to diff against each other.
    """
    assert _FRAMEWORK_CALLER_PREFIXES == LIBRARY_CALLER_PREFIXES, (
        "the shared library-caller prefix tuple changed; update the pin in this "
        "file deliberately and re-measure both APIs that depend on it"
    )


@pytest.mark.parametrize("prefix", sorted(_FRAMEWORK_CALLER_PREFIXES))
def test_every_declared_library_prefix_actually_filters(prefix):
    """EVERY prefix in the shared tuple must filter, on BOTH key forms.

    Two holes an adversarial review opened with running mutants, neither of which
    the identity guard below can see, because both keep the shared symbol:

    * a USE-SITE drift — import `_is_framework_caller`, then compare against an
      inline 2-prefix tuple in the METHOD branch only. That branch carries 1377
      of the corpus's 1378 dropped touches, so the feature becomes a complete
      no-op (tvleanback 8 touches -> 156, i.e. exactly `app_only=False`) while
      126 tests, black, ruff and mypy all stay green;
    * a TUPLE-CONTENT edit — deleting `"Lcom/google/android/"` (69 corpus
      touches) passed 126 tests. The only content assertions in the repo live in
      a corpus-gated test in tests/test_dangerous_api.py, so they skip in the CI
      leg with no APKs, and its integration half computes the expected total
      with the very predicate under test.

    Both survived because the hand-written fixtures exercise 2 of the 11
    prefixes, while `Landroid/support/` alone is 71% of what the corpus drops.
    Parametrising over the tuple ITSELF closes that by construction and keeps
    doing so as the tuple grows — a new prefix arrives with its own case.

    Five of the eleven have ZERO weight on the bundled corpus, so no corpus a/b
    could ever catch them moving; this is the only thing that does.
    """
    from dexllm.capability import summarize_capabilities

    caller = prefix + "some/Bundled;->plumbing()V"
    assert _is_framework_caller(caller), "fixture does not match its own prefix"

    # the METHOD branch (find_call_sites_to) — where the use-site drift lived
    method = _StubDk({_FOR_NAME: [caller]})
    assert (
        summarize_capabilities(method).matched_apis == 0
    ), f"a caller under {prefix!r} survived the method-key filter"
    assert summarize_capabilities(method, app_only=False).matched_apis == 1

    # …and the FIELD branch (find_methods_reading_field), a different lookup
    field_key = sorted(_FIELD_KEYS)[0]
    field = _StubDk({}, {field_key: [caller]})
    assert (
        summarize_capabilities(field).matched_apis == 0
    ), f"a caller under {prefix!r} survived the field-key filter"
    assert summarize_capabilities(field, app_only=False).matched_apis == 1


def test_a_filtered_report_says_what_it_dropped():
    """An empty report under the default must not read as "the APK does none of it".

    This module RAISES on an unknown `only_categories` tag with the reason that
    "silently returning an empty report would be indistinguishable from 'the APK
    exercises none of this'" — and the new default ships exactly that shape for
    11 of the 17 corpus sources that report anything at all (one of them drops
    301 touches across 30 APIs to a bare zero). `dropped_touches` / `dropped_apis`
    are what keep the module's own stance true of its own default.

    Under `app_only=False` both are 0: nothing was dropped, so the pre-dexllm#49
    reading of every other field is untouched.
    """
    from dexllm.capability import summarize_capabilities

    dk = _StubDk(
        {
            _FOR_NAME: [_LIB_CALLER, _APP_CALLER, _LIB_CALLER2],  # partly filtered
            _GET_DEVICE_ID: [_LIB_CALLER],  # dropped whole
        }
    )

    app = summarize_capabilities(dk)
    assert app.total_call_sites == 1
    assert app.dropped_touches == 3  # 2 off Class.forName + 1 whole getDeviceId
    assert app.dropped_apis == 1  # only getDeviceId left entirely
    # the zero-report case is the one that matters
    only_lib = summarize_capabilities(_StubDk({_GET_DEVICE_ID: [_LIB_CALLER]}))
    assert only_lib.matched_apis == 0 and only_lib.dropped_touches == 1

    every = summarize_capabilities(dk, app_only=False)
    assert every.dropped_touches == 0 and every.dropped_apis == 0


def test_the_app_only_default_is_the_same_on_every_layer():
    """dexllm#44 locked the argument NAME axis; this pins the DEFAULT.

    Two mutants an adversarial review ran, both green before this existed: the
    Protocol declaring `app_only: bool = False` (111 tests passed — mypy does not
    check a Protocol's default VALUES, so the contract a consumer type-checks
    against can invert with nothing objecting), and the MCP `input_schema` saying
    `"default": False` while the impl defaults to True (178 passed — the schema
    default is what an LLM reads to decide whether to pass the argument at all).
    """
    import inspect

    import dexllm
    from dexllm import tools
    from dexllm.sdk import ports
    from dexllm.sdk.adapter import DexKitAdapter

    def default(fn):
        return inspect.signature(fn).parameters["app_only"].default

    module_default = default(dexllm.summarize_capabilities)
    assert module_default is True, "the module function's own default moved"
    assert default(ports.CapabilityPort.summarize_capabilities) is module_default
    assert default(DexKitAdapter.summarize_capabilities) is module_default
    assert default(tools.TOOL_IMPLS["summarize_capabilities"]) is module_default

    schema = next(
        t for t in tools.TOOL_DEFINITIONS if t["name"] == "summarize_capabilities"
    )
    assert (
        schema["input_schema"]["properties"]["app_only"]["default"] is module_default
    ), "the advertised default disagrees with the one the impl applies"


def test_the_mcp_echo_reports_the_mode_that_was_actually_applied():
    """The echo must not affirm a belief the code did not act on.

    `tools.execute` is also the in-process dispatcher for the HTTP / agent loop
    and validates nothing, so a model's `"false"` (a common JSON-boolean slip)
    arrives as a truthy STRING: the counts are filtered, and echoing the argument
    verbatim would report `'false'` beside app-only numbers — the payload
    agreeing with the wrong belief, which is the single thing the echo exists to
    prevent.
    """
    from dexllm import tools

    dk = _StubDk({_FOR_NAME: [_LIB_CALLER, _APP_CALLER]})

    out = tools.execute("summarize_capabilities", {"app_only": "false"}, dk)
    assert out["total_call_sites"] == 1, "a truthy string must filter"
    assert out["app_only"] is True, "the echo must state the mode that was applied"

    assert (
        tools.execute("summarize_capabilities", {"app_only": 0}, dk)["app_only"]
        is False
    )
    assert tools.execute("summarize_capabilities", {}, dk)["dropped_touches"] == 1
