"""Typed stub for the pybind11 native module ``dexllm._dexkit_core``.

The native extension carries no static type information, so this ``.pyi`` is the
typed shadow of the API bound in ``native/binding/module.cpp``
(``PYBIND11_MODULE(_dexkit_core, m)``) plus the Python-side convenience
properties attached in ``src/dexllm/_enrich.py``.

Runtime is the source of truth. When a binding changes, update module.cpp first,
then reflect the added/removed/renamed ``.def(...)`` / ``py::class_`` attribute
here. Do not advertise names the runtime does not export.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any, TypedDict, overload

# ── dict-returning shapes (structural contracts) ─────────────────────────────

class _IdentifyResult(TypedDict):
    format: str
    is_apk: bool
    has_manifest: bool
    dex_count: int

class _VerifyStatus(TypedDict):
    dex_id: int
    name: str
    valid: bool
    reason: str

class _DecompiledMethodWithPc(TypedDict):
    source: str
    pc_map: list[tuple[int, int]]  # (line_1based, byte_off)

class _MethodAstResult(TypedDict):
    found: bool
    cls_name: str
    name: str
    proto: str
    ret_type: str
    params_type: list[str]
    access: list[str]
    source: str
    ast: dict[str, Any] | None  # None for an external / not-found method
    pc_map: list[tuple[int, int]]  # (statement_seq, byte_off)

class _PermissionCallerRow(TypedDict):
    api: str
    descriptors: list[str]
    callers: list[str]

class _PermissionCallerGroup(TypedDict):
    perm: str
    protectionLevel: str
    rows: list[_PermissionCallerRow]

# ── module-level functions ───────────────────────────────────────────────────

def identify(path: str) -> _IdentifyResult: ...
def verify(path: str, lenient: bool = ...) -> list[_VerifyStatus]: ...
def is_framework_descriptor(descriptor: str) -> bool: ...

# ── pybind return-object classes (read-only) ─────────────────────────────────

class ExternalTypeRef:
    @property
    def descriptor(self) -> str: ...
    @property
    def referenced_in_dex_ids(self) -> list[int]: ...
    # attached by _enrich.py
    @property
    def java_name(self) -> str: ...

class ExternalMethodRef:
    @property
    def class_descriptor(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def proto(self) -> str: ...
    @property
    def signature(self) -> str: ...
    @property
    def referenced_in_dex_ids(self) -> list[int]: ...
    # attached by _enrich.py
    @property
    def java_class(self) -> str: ...
    @property
    def parameters(self) -> list[str]: ...
    @property
    def return_type(self) -> str: ...
    @property
    def java_signature(self) -> str: ...
    @property
    def is_constructor(self) -> bool: ...
    @property
    def is_static_initializer(self) -> bool: ...

class ExternalFieldRef:
    @property
    def class_descriptor(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def type(self) -> str: ...
    @property
    def referenced_in_dex_ids(self) -> list[int]: ...
    # attached by _enrich.py
    @property
    def java_class(self) -> str: ...
    @property
    def java_type(self) -> str: ...
    @property
    def signature(self) -> str: ...
    @property
    def java_signature(self) -> str: ...

class ClassMatch:
    @property
    def descriptor(self) -> str: ...
    @property
    def dex_id(self) -> int: ...
    @property
    def class_id(self) -> int: ...

class MethodMatch:
    @property
    def descriptor(self) -> str: ...
    @property
    def dex_id(self) -> int: ...
    @property
    def method_id(self) -> int: ...

class FieldMatch:
    @property
    def descriptor(self) -> str: ...
    @property
    def dex_id(self) -> int: ...
    @property
    def field_id(self) -> int: ...

class ClassMemberField:
    @property
    def name(self) -> str: ...
    @property
    def type(self) -> str: ...
    @property
    def access_flags(self) -> int: ...

class ClassMemberMethod:
    @property
    def name(self) -> str: ...
    @property
    def proto(self) -> str: ...
    @property
    def access_flags(self) -> int: ...

class ClassSummary:
    @property
    def descriptor(self) -> str: ...
    @property
    def is_internal(self) -> bool: ...
    @property
    def dex_id(self) -> int: ...
    @property
    def access_flags(self) -> int: ...
    @property
    def superclass_descriptor(self) -> str: ...
    @property
    def interface_descriptors(self) -> list[str]: ...
    @property
    def fields(self) -> list[ClassMemberField]: ...
    @property
    def methods(self) -> list[ClassMemberMethod]: ...
    @property
    def source_file(self) -> str: ...

class ArgOrigin:
    # The raw pybind object populates every field (empty-string / 0 default when
    # the ``kind`` does not carry it); the typed dexllm.sdk.ArgOrigin is the
    # derived, Optional-narrowed view.
    @property
    def kind(self) -> str: ...
    @property
    def reg_num(self) -> int: ...
    @property
    def string_value(self) -> str: ...
    @property
    def int_value(self) -> int: ...
    @property
    def class_descriptor(self) -> str: ...
    @property
    def field_signature(self) -> str: ...
    @property
    def method_signature(self) -> str: ...
    @property
    def parameter_index(self) -> int: ...
    @property
    def crossed_branch(self) -> bool: ...

class CallSite:
    """One invoke edge; which half is FIXED depends on the producing direction.

    find_call_sites_to(X) fixes callee_descriptor and varies caller_*;
    find_call_sites_from(M) fixes caller_* and varies callee_descriptor.
    bytecode_offset is always an offset into the CALLER's instruction stream.
    One entry per invoke INSTRUCTION — a caller that invokes the target twice
    appears twice.
    """

    @property
    def caller_dex_id(self) -> int: ...
    @property
    def caller_method_idx(self) -> int:
        """Dex-LOCAL method_ids index — meaningful only with caller_dex_id."""

    @property
    def caller_descriptor(self) -> str: ...
    @property
    def callee_descriptor(self) -> str: ...
    @property
    def bytecode_offset(self) -> int: ...
    @property
    def invoke_opcode(self) -> int: ...

class ResolvedCallSite:
    """A CallSite plus a resolved origin per argument.

    Only resolve_call_args produces it, so callee_descriptor is fixed and the
    caller_* fields vary.
    """

    @property
    def caller_dex_id(self) -> int: ...
    @property
    def caller_method_idx(self) -> int:
        """Dex-LOCAL method_ids index — meaningful only with caller_dex_id."""

    @property
    def caller_descriptor(self) -> str: ...
    @property
    def callee_descriptor(self) -> str: ...
    @property
    def bytecode_offset(self) -> int: ...
    @property
    def invoke_opcode(self) -> int: ...
    @property
    def args(self) -> list[ArgOrigin]: ...

class TypeReferences:
    @property
    def fields(self) -> list[str]: ...
    @property
    def methods_returning(self) -> list[str]: ...
    @property
    def methods_with_param(self) -> list[str]: ...

# ── the engine ───────────────────────────────────────────────────────────────

class DexKit:
    @overload
    def __init__(self, apk_path: str, lenient: bool = False) -> None: ...
    @overload
    def __init__(self, sources: Sequence[str], lenient: bool = False) -> None: ...

    # load / container
    def dex_count(self) -> int: ...
    def apk_path(self) -> str: ...
    def sources(self) -> list[str]: ...
    def verify_report(self) -> list[_VerifyStatus]: ...
    def locate_class_dex(self, class_descriptor: str) -> int: ...

    # enumeration (all-dex + per-dex)
    def list_classes(self) -> list[str]: ...
    def list_classes_in_dex(self, dex_id: int) -> list[str]: ...
    def list_class_methods(self, class_descriptor: str) -> list[str]: ...
    def list_field_descriptors(self) -> list[str]: ...
    def list_field_descriptors_in_dex(self, dex_id: int) -> list[str]: ...
    def list_method_descriptors(self) -> list[str]: ...
    def list_method_descriptors_in_dex(self, dex_id: int) -> list[str]: ...
    def list_value_strings(self) -> list[str]: ...
    def list_class_strings(self, class_descriptor: str) -> list[str]: ...
    def list_method_strings(self, method_descriptor: str) -> list[str]: ...
    def extract_dex_bytes(self, dex_id: int) -> bytes: ...

    # class inspection / external refs
    def get_class_summary(self, descriptor: str) -> ClassSummary: ...
    def list_external_type_refs(
        self, framework_only: bool = True
    ) -> list[ExternalTypeRef]: ...
    def list_external_method_refs(
        self, framework_only: bool = True
    ) -> list[ExternalMethodRef]: ...
    def list_external_field_refs(
        self, framework_only: bool = True
    ) -> list[ExternalFieldRef]: ...

    # cross-reference
    def find_call_sites_to(self, api_descriptor: str) -> list[CallSite]:
        """Call sites invoking the API — its CALLERS (callee fixed, caller varies)."""

    def find_call_sites_from(self, method_descriptor: str) -> list[CallSite]:
        """Call sites inside the method — its CALLEES (caller fixed, callee varies)."""
    # deprecated aliases of the two above (pre-rename names)
    def find_call_sites_to_api(self, api_descriptor: str) -> list[CallSite]: ...
    def find_call_sites_from_method(self, method_descriptor: str) -> list[CallSite]: ...
    def resolve_call_args(self, api_descriptor: str) -> list[ResolvedCallSite]: ...
    def find_methods_reading_field(self, field_descriptor: str) -> list[str]: ...
    def find_methods_writing_field(self, field_descriptor: str) -> list[str]: ...
    # deprecated aliases of the two above (pre-rename names)
    def find_field_read_methods(self, field_descriptor: str) -> list[str]: ...
    def find_field_write_methods(self, field_descriptor: str) -> list[str]: ...
    def find_type_references(self, type_descriptor: str) -> TypeReferences: ...

    # search (L1–L7)
    def find_classes_by_name(
        self,
        name: str,
        match_type: str = "contains",
        ignore_case: bool = False,
    ) -> list[ClassMatch]: ...
    def find_classes_using_strings(
        self,
        strings: Sequence[str],
        match_type: str = "contains",
        ignore_case: bool = False,
    ) -> list[ClassMatch]: ...
    def find_classes_declaring_strings(
        self,
        strings: Sequence[str],
        match_type: str = "contains",
        ignore_case: bool = False,
    ) -> list[ClassMatch]: ...
    def find_methods_using_strings(
        self,
        strings: Sequence[str],
        match_type: str = "contains",
        ignore_case: bool = False,
    ) -> list[MethodMatch]: ...
    def batch_find_classes_using_strings(
        self,
        query_map: Mapping[str, Sequence[str]],
        match_type: str = "contains",
        ignore_case: bool = False,
    ) -> dict[str, list[ClassMatch]]: ...
    def batch_find_methods_using_strings(
        self,
        query_map: Mapping[str, Sequence[str]],
        match_type: str = "contains",
        ignore_case: bool = False,
    ) -> dict[str, list[MethodMatch]]: ...
    def find_methods_by_name(
        self,
        name: str,
        match_type: str = "contains",
        declaring_class: str = "",
        ignore_case: bool = False,
    ) -> list[MethodMatch]: ...
    def find_classes_by_annotation(
        self, annotation_class: str, match_type: str = "equals"
    ) -> list[ClassMatch]: ...
    def find_methods_by_annotation(
        self, annotation_class: str, match_type: str = "equals"
    ) -> list[MethodMatch]: ...
    def find_classes_by_super(
        self, super_class: str, match_type: str = "equals"
    ) -> list[ClassMatch]: ...
    def find_classes_implementing(
        self, interface_class: str, match_type: str = "equals"
    ) -> list[ClassMatch]: ...
    def find_methods_using_int_literals(
        self, values: Sequence[int]
    ) -> list[MethodMatch]: ...
    def find_methods_using_double_literals(
        self, values: Sequence[float]
    ) -> list[MethodMatch]: ...

    # decompile / smali
    def decompile_method(self, method_descriptor: str) -> str:
        """Java text. The suffixed variants add structure to the SAME output."""

    def decompile_method_with_pc_map(
        self, method_descriptor: str
    ) -> _DecompiledMethodWithPc: ...
    def decompile_class(self, class_descriptor: str) -> str: ...
    # deprecated aliases of the three above (pre-rename names)
    def decompile_method_java(self, method_descriptor: str) -> str: ...
    def decompile_method_java_with_pc(
        self, method_descriptor: str
    ) -> _DecompiledMethodWithPc: ...
    def decompile_class_java(self, class_descriptor: str) -> str: ...
    def decompile_method_ast(
        self, method_descriptor: str, include_source: bool = True
    ) -> _MethodAstResult: ...
    def render_method_smali(self, method_descriptor: str) -> str: ...
    def render_class_smali(self, class_descriptor: str) -> str: ...

    # permissions
    def permission_callers(
        self, app_only: bool = True
    ) -> list[_PermissionCallerGroup]: ...

    # caches / lifecycle — actions are verb-first, read-only accessors are nouns
    def warm_analysis_caches(self) -> None: ...
    def clear_decompiler_cache(self) -> None: ...
    def set_decompiler_cache_capacity(self, cap: int) -> None: ...
    def decompiler_cache_size(self) -> int: ...
    def decompiler_cache_capacity(self) -> int: ...
    # deprecated aliases of the two ACTIONS above (clear / set_..._capacity)
    def decompiler_clear_cache(self) -> None: ...
    def decompiler_set_cache_capacity(self, cap: int) -> None: ...
