#!/usr/bin/env python3
"""Codegen: embed the dangerous permission→API table into a C++ header.

Issue #13 — the WASM binding needs the permission-caller analysis with the AOSP
data BUNDLED (single source of truth = the engine's ``src/dexllm/data``). Rather
than re-implement the intricate Java/Kotlin signature normalisation in C++, we run
the EXISTING Python normaliser (``dangerous_api._parse_api`` / ``_param_simple`` /
``_overload_index``) here at build time and emit a header with the dataset already
reduced to ``(perm, class_dotted, method, simple-param-types)`` plus the overload
arity map. The C++ join (``native/core_ext/analysis.cpp``) then only has to parse
Dalvik protos (simple) and compare — the hard normalisation is done once, in one
place, by the same code the Python path uses.

Regenerate after editing ``src/dexllm/data/dangerous_perm_api.json``:
    python scripts/gen_perm_api_data.py
The generated header is committed (checked in) so the build needs no Python.
"""
from __future__ import annotations

import pathlib

from dexllm.dangerous_api import _load_dangerous_map, _overload_index, _parse_api

OUT = (
    pathlib.Path(__file__).resolve().parent.parent
    / "native"
    / "core_ext"
    / "gen"
    / "perm_api_data.h"
)


def _cpp_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> None:
    table = _load_dangerous_map(None)  # bundled dangerous slice
    # Lock the ordering contract (adversarial-review): the C++ join returns groups
    # in this iteration order, while the Python API returns them in the bundled
    # JSON's insertion order. They agree ONLY while the JSON is perm-sorted; assert
    # it here so a future unsorted edit fails the codegen loudly instead of silently
    # diverging the two paths' group order.
    keys = list(table)
    assert keys == sorted(keys), (
        "dangerous_perm_api.json must be sorted by permission key so the C++ and "
        "Python group orders match; re-sort the JSON (or the source that emits it)."
    )
    overloads = _overload_index(table)

    # Flatten to method-call entries only (field/constant entries — types is None —
    # can never match a call ref, so they are dropped here, matching the Python
    # join which skips them).
    entries: list[tuple[str, str, str, str, tuple[str, ...]]] = []
    for perm in sorted(table):
        for sig in table[perm]:
            cls, method, types = _parse_api(sig)
            if types is None:
                continue
            entries.append((perm, cls, method, sig, types))

    lines: list[str] = []
    lines.append("// GENERATED by scripts/gen_perm_api_data.py — DO NOT EDIT.")
    lines.append(
        "// Source: src/dexllm/data/dangerous_perm_api.json (AOSP dangerous slice)."
    )
    lines.append("//")
    lines.append(
        "// The dataset's Java/Kotlin signatures are pre-normalised to simple param"
    )
    lines.append(
        "// types by the SAME code the Python API uses (dangerous_api._parse_api);"
    )
    lines.append(
        "// the C++ join only parses Dalvik protos + compares. See the codegen doc."
    )
    lines.append("#pragma once")
    lines.append("#include <map>")
    lines.append("#include <string>")
    lines.append("#include <utility>")
    lines.append("#include <vector>")
    lines.append("")
    lines.append("namespace dexkit::ext::gen {")
    lines.append("")
    lines.append("struct PermApiEntry {")
    lines.append("    std::string perm;")
    lines.append("    std::string cls;      // Java dotted, inner-class '.' separated")
    lines.append("    std::string method;   // dex name (a ctor keeps its class simple name)")
    lines.append("    std::string sig;      // the full dataset signature (output 'api' field)")
    lines.append("    std::vector<std::string> param_types;  // simple names; empty = 0-arity")
    lines.append("};")
    lines.append("")
    lines.append("// All dangerous perm → method-call API entries (fields dropped).")
    lines.append("inline const std::vector<PermApiEntry>& PermApiEntries() {")
    lines.append("    static const std::vector<PermApiEntry> kE = {")
    for perm, cls, method, sig, types in entries:
        params = ", ".join(_cpp_str(t) for t in types)
        lines.append(
            f"        {{{_cpp_str(perm)}, {_cpp_str(cls)}, {_cpp_str(method)}, "
            f"{_cpp_str(sig)}, {{{params}}}}},"
        )
    lines.append("    };")
    lines.append("    return kE;")
    lines.append("}")
    lines.append("")
    lines.append("// (class, method) -> {arity -> #distinct-signature overloads}. Drives the")
    lines.append("// overload-ambiguity check: a lone overload (or lone of an arity) matches on")
    lines.append("// arity alone, so a param-parse edge case can't drop a real hit.")
    lines.append(
        "inline const std::map<std::pair<std::string, std::string>, "
        "std::map<int, int>>&"
    )
    lines.append("OverloadCounts() {")
    lines.append(
        "    static const std::map<std::pair<std::string, std::string>, "
        "std::map<int, int>> kO = {"
    )
    for (cls, method), arity in sorted(overloads.items()):
        amap = ", ".join(f"{{{a}, {c}}}" for a, c in sorted(arity.items()))
        lines.append(
            f"        {{{{{_cpp_str(cls)}, {_cpp_str(method)}}}, {{{amap}}}}},"
        )
    lines.append("    };")
    lines.append("    return kO;")
    lines.append("}")
    lines.append("")
    lines.append("}  // namespace dexkit::ext::gen")
    lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(
        f"wrote {OUT} — {len(entries)} entries, {len(overloads)} (class,method) keys"
    )


if __name__ == "__main__":
    main()
