#!/usr/bin/env python3
"""Codegen: embed the Android API -> permission/category catalog into a C++ header.

Issue #13 (Phase 2) — the WASM binding needs summarize_capabilities with the
catalog BUNDLED (single source of truth = src/dexllm/data/android_api_map.json), so
the C++ port (native/core_ext/analysis.cpp SummarizeCapabilities) and the pybind /
embind bindings all share one catalog + join. Entries are emitted in the JSON's
insertion order — the same order dexllm.capability.summarize_capabilities iterates —
so api_hits (a list) and the aggregation are byte-identical between the two paths.

Regenerate after editing src/dexllm/data/android_api_map.json:
    python scripts/gen_android_api_data.py
The generated header is committed so the build needs no Python.
"""
from __future__ import annotations

import json
import pathlib

DATA = (
    pathlib.Path(__file__).resolve().parent.parent
    / "src" / "dexllm" / "data" / "android_api_map.json"
)
OUT = (
    pathlib.Path(__file__).resolve().parent.parent
    / "native" / "core_ext" / "gen" / "android_api_data.h"
)


def _cpp_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> None:
    catalog = json.loads(DATA.read_text())
    version = catalog.get("version", "unknown")
    entries = catalog["entries"]  # insertion order preserved (py3.7+)
    # Data-lint: keys are Dalvik method descriptors passed straight to
    # FindCallSitesToApi; they must be printable ASCII (byte-safe, no control char
    # to mangle the emitted string literal) and descriptor-shaped. Permission /
    # category labels likewise must be printable ASCII (they are emitted verbatim).
    for sig, meta in entries.items():
        assert sig.isascii() and sig.isprintable() and "->" in sig, (
            f"bad catalog key {sig!r}"
        )
        for label in meta.get("permissions", []) + meta.get("categories", []):
            assert label.isascii() and label.isprintable(), (
                f"catalog label {label!r} must be printable ASCII"
            )

    lines = [
        "// GENERATED by scripts/gen_android_api_data.py — DO NOT EDIT.",
        "// Android API -> permission/category catalog (issue #13, Phase 2).",
        "// Emitted in JSON insertion order (== capability.summarize_capabilities'",
        "// iteration order) so api_hits + aggregation are byte-identical.",
        "#pragma once",
        "",
        "#include <string>",
        "#include <string_view>",
        "#include <vector>",
        "",
        "namespace dexkit::ext::gen {",
        "",
        "struct CapabilityCatalogEntry {",
        "    std::string api_signature;",
        "    std::vector<std::string> permissions;  // catalog order (may be empty)",
        "    std::vector<std::string> categories;   // catalog order",
        "};",
        "",
        f"inline constexpr std::string_view kCapabilityCatalogVersion = "
        f"{_cpp_str(version)};",
        "",
        "inline const std::vector<CapabilityCatalogEntry>& CapabilityCatalog() {",
        "    static const std::vector<CapabilityCatalogEntry> kC = {",
    ]
    for sig, meta in entries.items():
        perms = ", ".join(_cpp_str(p) for p in meta.get("permissions", []))
        cats = ", ".join(_cpp_str(c) for c in meta.get("categories", []))
        lines.append(f"        {{{_cpp_str(sig)}, {{{perms}}}, {{{cats}}}}},")
    lines += [
        "    };",
        "    return kC;",
        "}",
        "",
        "}  // namespace dexkit::ext::gen",
        "",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({len(entries)} catalog entries, version {version})")


if __name__ == "__main__":
    main()
