#!/usr/bin/env python3
"""Codegen: embed the content:// provider-URI dataset into a C++ header.

Issue #13 — the WASM binding needs the content:// provider detection with the
AOSP-derived dataset BUNDLED (single source of truth = the engine's
``src/dexllm/data/content_uris.json``), so dexllm-web stops shipping its own copy.
The C++ join (``native/core_ext/ioc.cpp`` `DetectContentProviders`) only needs the
(uri, family) pairs — the dataset's provider-class metadata is not used by the
match — so we emit just those, sorted by URI (matching the Python path's sorted
iteration order for a byte-identical result).

Regenerate after editing ``src/dexllm/data/content_uris.json``:
    python scripts/gen_content_uris_data.py
The generated header is committed so the build needs no Python.
"""
from __future__ import annotations

import json
import pathlib

DATA = (
    pathlib.Path(__file__).resolve().parent.parent
    / "src" / "dexllm" / "data" / "content_uris.json"
)
OUT = (
    pathlib.Path(__file__).resolve().parent.parent
    / "native" / "core_ext" / "gen" / "content_uris_data.h"
)


def _cpp_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> None:
    dataset = json.loads(DATA.read_text())
    # Data-lint (adversarial-review): the C++ substring match is byte-identical to
    # Python's `uri in s` ONLY while every key is pure ASCII (an ASCII needle's
    # byte-search == its code-point search regardless of the haystack), and the
    # `content://` fast-filter is a no-op only while every key contains it. Enforce
    # both here so a bad dataset edit fails codegen loudly instead of silently
    # diverging the two paths (and `_cpp_str` never has to escape a control char).
    for uri, meta in dataset.items():
        family = meta["family"]
        for label, val in (("uri", uri), ("family", family)):
            assert val.isascii() and val.isprintable(), (
                f"content_uris.json {label} {val!r} must be printable ASCII "
                f"(the C++ byte-substring match assumes it)"
            )
        assert uri.startswith("content://"), (
            f"content_uris.json key {uri!r} must start with 'content://'"
        )
    rows = sorted((uri, meta["family"]) for uri, meta in dataset.items())
    lines = [
        "// GENERATED by scripts/gen_content_uris_data.py — DO NOT EDIT.",
        "// content:// provider-URI dataset (uri, family), sorted by URI (issue #13).",
        "#pragma once",
        "",
        "#include <string_view>",
        "#include <array>",
        "#include <utility>",
        "",
        "namespace dexkit::ext::gen {",
        "",
        f"inline constexpr std::array<std::pair<std::string_view, std::string_view>, "
        f"{len(rows)}>",
        "    kContentUris = {{",
    ]
    for uri, family in rows:
        lines.append(f"    {{{_cpp_str(uri)}, {_cpp_str(family)}}},")
    lines += ["}};", "", "}  // namespace dexkit::ext::gen", ""]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({len(rows)} content:// URIs)")


if __name__ == "__main__":
    main()
