#!/usr/bin/env python3
"""Codegen: Unicode `\\w` / `\\s` code-point ranges for the IoC scanners.

Issue #13. The Python IoC regexes run over `str` (Unicode code points), so `\\b`
(word boundary) and the URL body's `[^\\s…]` use Python's UNICODE `\\w` / `\\s`.
The C++ port (ioc.cpp) runs over UTF-8 bytes; to be byte-identical it must
classify a decoded code point exactly as Python `re` does. Rather than reimplement
the Unicode database, we emit the exact ranges from Python's OWN `re` engine at
build time (ground truth), the same drift-free codegen trick as gen_psl_data.py.

The vast majority of the touch-points are ASCII (real IoC values), but a value can
sit adjacent to a non-ASCII code point in a binary blob (e.g. a DER certificate's
C1 control byte before an embedded e-mail) — a byte-only heuristic misclassifies
those. Regenerate if the Unicode version bundled with Python changes:
    python scripts/gen_word_ranges.py
"""
from __future__ import annotations

import pathlib
import re

OUT = (
    pathlib.Path(__file__).resolve().parent.parent
    / "native"
    / "core_ext"
    / "gen"
    / "word_ranges.h"
)

MAX_CP = 0x110000


def _ranges(pattern: str) -> list[tuple[int, int]]:
    rx = re.compile(pattern)
    ranges: list[tuple[int, int]] = []
    lo: int | None = None
    for cp in range(MAX_CP):
        hit = rx.match(chr(cp)) is not None
        if hit and lo is None:
            lo = cp
        elif not hit and lo is not None:
            ranges.append((lo, cp - 1))
            lo = None
    if lo is not None:
        ranges.append((lo, MAX_CP - 1))
    return ranges


def _emit(name: str, ranges: list[tuple[int, int]]) -> list[str]:
    lines = [
        f"inline constexpr std::array<std::pair<char32_t, char32_t>, "
        f"{len(ranges)}>",
        f"    {name} = {{{{",
    ]
    for lo, hi in ranges:
        lines.append(f"    {{0x{lo:X}, 0x{hi:X}}},")
    lines += ["}};", ""]
    return lines


def main() -> None:
    word = _ranges(r"\w")
    space = _ranges(r"\s")
    out = [
        "// GENERATED by scripts/gen_word_ranges.py — DO NOT EDIT.",
        "// Unicode \\w / \\s code-point ranges (Python re ground truth) for the",
        "// IoC scanners' \\b / \\s semantics (issue #13). Sorted, non-overlapping;",
        "// binary-searched at runtime after UTF-8 decoding a code point.",
        "#pragma once",
        "",
        "#include <array>",
        "#include <utility>",
        "",
        "namespace dexkit::ext::gen {",
        "",
    ]
    out += _emit("kWordRanges", word)
    out += _emit("kSpaceRanges", space)
    out += ["}  // namespace dexkit::ext::gen", ""]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out))
    print(f"wrote {OUT} (word ranges={len(word)}, space ranges={len(space)})")


if __name__ == "__main__":
    main()
