#!/usr/bin/env python3
"""Codegen: embed the public-suffix list (ICANN section) into a C++ header.

Issue #13 — the WASM binding needs the IoC domain-validation (``extract_iocs``'s
``_valid_domain`` / URL-host fold) with the public-suffix data BUNDLED, so
``dexllm-web`` stops shipping its own copy and the two paths cannot drift. The
engine's IoC path validates bare domains with ``tldextract`` (the Mozilla PSL);
this header carries the SAME suffix set so the C++ port (``public_suffix.cpp``)
resolves suffixes identically.

Drift-free by construction — the suffix set is read from tldextract's OWN bundled
snapshot via tldextract's OWN parser (``extract_tlds_from_suffix_list``), then each
label is emitted in its **ASCII / punycode (xn--) form**. That matters because:

  * tldextract stores DECODED (unicode) suffixes in its trie and decodes each input
    label with ``_decode_punycode`` before matching (so ``foo.xn--p1ai`` matches the
    stored ``рф``).
  * A dex value-string is scanned by an ASCII-only host regex, so the only input
    form we ever see is ASCII (``xn--p1ai``), never the unicode ``рф``.

  So we key the C++ trie on the ASCII form and match the ASCII input DIRECTLY —
  no punycode decode in C++, and provably equivalent to tldextract for ASCII input
  (``_decode_punycode(ascii_xn) == _decode_punycode(unicode)`` — asserted below).

The private-domains section is EXCLUDED (tldextract's ``include_psl_private_domains``
defaults to False), matching ``ioc.py``'s ``TLDExtract(suffix_list_urls=(), …)``.

Regenerate after a tldextract upgrade (the snapshot ships with the package):
    python scripts/gen_psl_data.py
The generated header is committed so the build needs no Python / tldextract.
"""
from __future__ import annotations

import codecs
import pathlib

import tldextract
from tldextract.suffix_list import extract_tlds_from_suffix_list
from tldextract.tldextract import _decode_punycode

OUT = (
    pathlib.Path(__file__).resolve().parent.parent
    / "native"
    / "core_ext"
    / "gen"
    / "psl_data.h"
)


def _ascii_label(label: str) -> str:
    """The ASCII (xn--) form of a suffix label, matching what a dex string carries.

    A ``*`` wildcard / ``!exception`` marker or an already-ASCII label passes
    through; a unicode label is punycode-encoded. The result is verified to decode
    (via tldextract's own ``_decode_punycode``) back to the same value tldextract
    would key its trie on — so ASCII-trie + ASCII-input is equivalent to
    tldextract's unicode-trie + decoded-input for every ASCII input we can see.
    """
    lo = label.lower()
    if lo.isascii():
        return lo
    enc = codecs.encode(lo, "idna").decode("ascii")
    assert _decode_punycode(enc) == _decode_punycode(lo), (
        f"punycode round-trip mismatch for {label!r}: {enc!r}"
    )
    return enc


def _ascii_suffix(suffix: str) -> str:
    return ".".join(_ascii_label(p) for p in suffix.split("."))


def _cpp_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> None:
    # Read tldextract's bundled snapshot with tldextract's OWN parser (single source
    # of truth for both the exact set and the public/private split).
    snapshot = pathlib.Path(tldextract.__file__).parent / ".tld_set_snapshot"
    public_tlds, _private = extract_tlds_from_suffix_list(
        snapshot.read_text(encoding="utf-8")
    )
    # Dedupe (the parser can repeat) and order deterministically.
    ascii_suffixes = sorted({_ascii_suffix(s) for s in public_tlds})

    lines = [
        "// GENERATED by scripts/gen_psl_data.py — DO NOT EDIT.",
        "// Public-suffix list (ICANN section) for IoC domain validation (issue #13).",
        "// Labels in ASCII/punycode form; see the codegen script for the equivalence",
        "// argument (ASCII-trie + ASCII-input == tldextract's unicode-trie + decode).",
        "#pragma once",
        "",
        "#include <string_view>",
        "#include <array>",
        "",
        "namespace dexkit::ext::gen {",
        "",
        f"inline constexpr std::array<std::string_view, {len(ascii_suffixes)}>",
        "    kPublicSuffixes = {{",
    ]
    for s in ascii_suffixes:
        lines.append(f"    {_cpp_str(s)},")
    lines += [
        "}};",
        "",
        "}  // namespace dexkit::ext::gen",
        "",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({len(ascii_suffixes)} public suffixes)")


if __name__ == "__main__":
    main()
